#!/usr/bin/env python
#
# License: BSD
#   https://raw.github.com/robotics-in-concert/rocon_multimaster/master/rocon_gateway_graph/LICENSE
#
##############################################################################
# Imports
##############################################################################

import sys
from rqt_gui.main import Main

##############################################################################
# Main
##############################################################################

main = Main()
sys.exit(main.main(sys.argv, standalone='rocon_gateway_graph'))
