#!/usr/bin/env python
#
##############################################################################
# Imports
##############################################################################
#system
import sys
import os
#ros
import rospy
#concert message and service
from concert_msgs.msg import ConcertInfo

temp_icon_path = "%s/.ros/rocon/remocon/image/"%(os.getenv("HOME"))
if not os.path.isdir(temp_icon_path):
    os.makedirs(temp_icon_path)

def _info_callback(data):
    concert_name=data.name       
    icon_name = data.icon.resource_name.split('/').pop()
    icon = open(temp_icon_path+icon_name,'w')
    icon.write(data.icon.data)
    icon.close()  
    
    print concert_name
    print data.description
    print icon_name
    
    rospy.signal_shutdown("shut down check_up")       

def _check_valid_concert():
    ret_value = False
    topic_list = rospy.get_published_topics()
    for k in topic_list:
        if k[0] == '/concert/info':
            ret_value = True
            break                        
    return ret_value   

if __name__ == "__main__":
     
    concert_ip = sys.argv[1] #ip
    host_name=sys.argv[2]

    os.environ["ROS_MASTER_URI"] = 'http://'+concert_ip+':'+"11311"
    os.environ["ROS_HOSTNAME"] = host_name
    
    rospy.init_node("check_up",anonymous = True, disable_signals=True)
    if not _check_valid_concert():
        print "Unknown"
        print "Unknown."
        print "Unknown.png"
        rospy.signal_shutdown("shut down check_up")
    info_sub = rospy.Subscriber("/concert/info", ConcertInfo , _info_callback)

    while not rospy.is_shutdown():
        rospy.sleep(rospy.Duration(0.1))
        pass
    
