#!/usr/bin/env python
#
# License: BSD
#   https://raw.github.com/robotics-in-concert/rocon_multimaster/master/rocon_remote_control/LICENSE
#
##############################################################################
# Imports
##############################################################################

import sys, signal, string, atexit
#from rqt_gui.main import Main
from PyQt4.QtGui import QAction, QApplication, QFrame, QIcon,QMainWindow, QMenu, QSystemTrayIcon
from PyQt4.QtCore import QTimer

from os import path
src_dir = path.join(path.dirname(__file__), '../src/rocon_remocon')
sys.path.append(src_dir)

import remocon

##############################################################################
# Main
##############################################################################.

def signal_handler(signum, f): 
    if signum == signal.SIGINT:
        sys.exit()

if __name__ == "__main__":
    signal.signal(signal.SIGINT, signal_handler)
    
    index = sys.argv[1] #name
    name = sys.argv[2] #ip
    ip = sys.argv[3] #ip
    host_name = sys.argv[4] #ip

    app = QApplication(sys.argv)
    # Let the interpreter run each 200 ms.
    timer = QTimer()
    timer.start(200)  
    timer.timeout.connect(lambda: None)
    
    myapp = remocon.RemoconRole(None, "My System Tray App",index,name,ip,host_name)
    atexit.register(myapp._uninit_role_list)
    app.exec_()

sys.path.remove(src_dir)


