#!/usr/bin/env python
##############################################################################
# Imports
##############################################################################
#system
import sys
import signal
import string
import atexit
#pyqt
from PyQt4.QtGui import QAction, QApplication, QFrame, QIcon,QMainWindow, QMenu, QSystemTrayIcon
from PyQt4.QtCore import QTimer
#rocon
import rocon_remocon

##############################################################################
# Main
##############################################################################.

def signal_handler(signum, f): 
    if signum == signal.SIGINT:
        sys.exit()

if __name__ == "__main__":
    signal.signal(signal.SIGINT, signal_handler)
    
    index = sys.argv[1] #name
    name = sys.argv[2] #ip
    ip = sys.argv[3] #ip
    host_name = sys.argv[4] #ip

    app = QApplication(sys.argv)
    # Let the interpreter run each 200 ms.
    timer = QTimer()
    timer.start(200)  
    timer.timeout.connect(lambda: None)
    
    myapp = rocon_remocon.RemoconRole(None, "My System Tray App",index,name,ip,host_name)
    atexit.register(myapp._uninit_role_list)
    app.exec_()

