#!/usr/bin/env python
#
import sys
import os

import rospy
from concert_msgs.msg import ConcertInfo

icon_path = os.path.join(os.path.dirname(os.path.abspath(__file__)),"../resources/images/")

def _info_callback(data):
    concert_name=data.name       
    icon_name = concert_name+'.'+data.icon.format
    icon = open(icon_path+icon_name,'w')
    icon.write(data.icon.data)
    icon.close()  
    
    print concert_name
    print data.description
    print icon_name
    
    rospy.signal_shutdown("shut down check_up")

def _check_valid_concert():
    ret_value = False
    topic_list = rospy.get_published_topics()
    for k in topic_list:
        if k[0] == '/info':
            ret_value = True
            break                        
    return ret_value   

if __name__ == "__main__":
    concert_ip = sys.argv[1] #ip
    os.environ["ROS_MASTER_URI"] = 'http://'+concert_ip+':'+"11311"
    os.environ["ROS_HOSTNAME"] = '192.168.10.109'
    rospy.init_node("check_up",anonymous = True, disable_signals=True)
    if not _check_valid_concert():
        print "Unknown"
        print "Unknown."
        print "Unknown.jpg"
        sys.exit()
    info_sub = rospy.Subscriber("/info", ConcertInfo , _info_callback)
    while not rospy.is_shutdown():
        pass
    
