#!/usr/bin/env python
#
# License: BSD
#   https://raw.github.com/robotics-in-concert/rocon_qt_gui/license/LICENSE
#
##############################################################################
# Imports
##############################################################################
#system
import sys
import signal
#pyqt
from PyQt4.QtGui import QApplication  # QAction, QFrame, QIcon,QMainWindow, QMenu, QSystemTrayIcon
from PyQt4.QtCore import QTimer  # Qt

#rocon
import rocon_remocon

##############################################################################
# Globals
##############################################################################.

app = None
myapp = None

##############################################################################
# Methods
##############################################################################.


def signal_handler(signum, f):
    print "[main] Interrupt"
    if signum == signal.SIGINT:
        app.exit(0)

##############################################################################
# Main
##############################################################################.


if __name__ == "__main__":

    signal.signal(signal.SIGINT, signal_handler)
    app = QApplication(sys.argv)
    # Let the interpreter run each 200 ms.
    timer = QTimer()
    timer.start(200)
    timer.timeout.connect(lambda: None)
    myapp = rocon_remocon.remocon.RemoconMain(None, "My System Tray App", app)
    app.exec_()
    print "rocon_remocon: Main end"
