#!/usr/bin/env python
#
# License: BSD
#   https://raw.github.com/robotics-in-concert/rocon_qt_gui/license/LICENSE
#
##############################################################################
# Imports
##############################################################################

import os
import sys

import rospy
import rocon_remocon
import rocon_python_comms
import rocon_std_msgs.msg as rocon_std_msgs

##############################################################################
# Main
##############################################################################

if __name__ == "__main__":
    ros_master_uri = sys.argv[1]
    host_name = sys.argv[2]

    os.environ["ROS_MASTER_URI"] = ros_master_uri
    os.environ["ROS_HOSTNAME"] = host_name

    rospy.init_node("rocon_remocon_checker", anonymous=True)

    try:
        topic_name = rocon_python_comms.find_topic('rocon_std_msgs/MasterInfo', timeout=rospy.rostime.Duration(5.0), unique=True)
        master_info = rocon_python_comms.SubscriberProxy(topic_name, rocon_std_msgs.MasterInfo)()
        print master_info.name
        print master_info.description
        icon_name = master_info.icon.resource_name.split('/').pop()
        if master_info.icon.data:
            rocon_remocon.setup_home_dirs()
            icon = open(os.path.join(rocon_remocon.get_icon_cache_home(), icon_name), 'w')
            icon.write(master_info.icon.data)
            icon.close()
        print icon_name
    except rocon_python_comms.NotFoundException as e:
        print "Unknown"
        print "Unknown."
        print "unknown.png"
